/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Structured document representation for Zotero. Defines a semantic content tree of block nodes (paragraphs, headings, lists, tables, images, math, code, captions, notes, blockquotes) with inline text styling, cross-references, source anchors, page geometry, and a document outline. Supports PDF, EPUB, and snapshot sources.
 */
export interface StructuredDocumentText {
  /**
   * Semantic version of this schema (major/minor/patch).
   */
  schemaVersion: string;
  /**
   * Document-level extraction and source metadata.
   */
  metadata: {
    /**
     * Processor that generated this document.
     */
    processor: {
      /**
       * Processor type.
       */
      type: "pdf" | "epub" | "snapshot";
      /**
       * Processor output version. Exact matches are used for cache freshness.
       */
      version: number;
    };
    /**
     * Creation time in ISO 8601.
     */
    dateCreated: string;
    /**
     * Total character count of extracted text content (sum over all text nodes).
     */
    characterCount?: number;
    /**
     * Source document identity and source-specific properties.
     */
    source: {
      /**
       * MIME type of the source.
       */
      contentType: "application/pdf" | "application/epub+zip" | "text/html" | "application/xhtml+xml";
      /**
       * MD5 hash of the source file (32-char hex string) used to detect changes.
       */
      hash: string;
      /**
       * Size of the original source file in bytes.
       */
      fileSize?: number;
      /**
       * Source-specific document properties. For PDF: PDFFormatVersion, Title, Author, Subject, Keywords, Creator, Producer, CreationDate, ModDate, Language, and any custom properties. For EPUB: dc:title, dc:creator, dc:language, etc. For snapshot: title, url, charset. Shape is open-ended.
       */
      properties?: {
        [k: string]: unknown;
      };
    };
  };
  /**
   * Document-level catalog structures that point into content.
   */
  catalog: {
    /**
     * Document outline (table of contents).
     */
    outline: OutlineItem[];
    /**
     * Per-page info. For PDF: physical pages. For EPUB: page mappings (physical page numbers or EPUB locations).
     */
    pages: PageInfo[];
    /**
     * For EPUB: whether pages represent physical page numbers from the source or synthetic EPUB locations.
     */
    pageMappingType?: "physical" | "locations";
    /**
     * For snapshots: skeleton of the source DOM - every element containing extracted text, plus its ancestors - with body text offsets. Lets consumers resolve and generate CssSelector/TextPositionSelector positions rooted at arbitrary elements without access to the source DOM.
     */
    domMap?: DomMapNode[];
  };
  /**
   * Top-level block nodes (headings, paragraphs, lists, tables, etc.).
   */
  content: ContentBlockNode[];
}
/**
 * Path to the corresponding heading or block in the content tree.
 *
 * @minItems 1
 */
export type RefPath = [number, ...number[]];
/**
 * Target location in the source or an external URL.
 */
export type Target = {
  /**
   * Position in the source document.
   */
  position?: {
    pageIndex?: number;
    /**
     * Page rect: [x1, y1, x2, y2].
     *
     * @minItems 4
     * @maxItems 4
     */
    rect?: [number, number, number, number];
  };
  /**
   * External URL.
   */
  url?: string;
};
/**
 * Half-open content boundary range covered by this page. Empty pages use equal boundaries.
 *
 * @minItems 2
 * @maxItems 2
 */
export type PageContentRange = [PageContentBoundary, PageContentBoundary];
/**
 * Boundary position in document content. A top-level value equal to content.length is valid and means document end; deeper paths may include a terminal text offset.
 *
 * @minItems 1
 */
export type PageContentBoundary = [number, ...number[]];
/**
 * Block nodes valid as document content, inside containers, and at top level. Excludes structural-only children (ListItemNode, TableRowNode, TableCellNode) that only appear inside their parent containers.
 */
export type ContentBlockNode =
  | ParagraphNode
  | HeadingNode
  | MathNode
  | ImageNode
  | BlockquoteNode
  | ListNode
  | TableNode
  | CaptionNode
  | NoteNode
  | PreformattedNode;
/**
 * Referenced target nodes. Array because one mention can resolve to multiple targets (e.g. "[2-5]" -> multiple bibliography entries, or ambiguous author-name citations).
 */
export type RefsArray = RefPath[];
/**
 * Nodes that reference this one (inverse of refs).
 */
export type BackRefsArray = RefPath[];
/**
 * Link from this node back to the source document. PDF uses PdfAnchor (pageRects/textMap). EPUB and snapshot use DomAnchor: a selectorMap field that compactly encodes source locations (blocks, EPUB text nodes), or a body text-stream offset (snapshot text nodes, resolved against catalog.domMap). Use the dom/epub decode and dom/snapshot dommap modules to expand and resolve.
 */
export type Anchor = PdfAnchor | DomAnchor;
/**
 * PDF source anchor with page geometry and/or text layout map. `textMap` validation is intentionally permissive (string-only); consumers should parse and validate decoded run structure at runtime.
 */
export type PdfAnchor = {
  /**
   * Bounding boxes on source pages.
   *
   * @minItems 1
   */
  pageRects?: [PageRect, ...PageRect[]];
  /**
   * Packed text layout encoded as a JSON string. Decoded value is an array of runs; each run is `[header, pageIndex, minX, minY, maxX, maxY, ...widths]`. Header bits: bit 0 = trailing soft hyphen marker, bits 1-2 = axis direction, bit 3 = right-to-left flag. Width entries are either numeric widths or `[delta, width]` pairs.
   */
  textMap?: string;
};
/**
 * Block bounding box: [pageIndex, x1, y1, x2, y2] (page coordinates).
 *
 * @minItems 5
 * @maxItems 5
 */
export type PageRect = [number, number, number, number, number];
/**
 * Compact anchor for EPUB and snapshot blocks and text nodes. For blocks, selectorMap is an absolute location: EPUB CFI path (starts with '/') or snapshot CSS selector. For EPUB text nodes, selectorMap is a CFI suffix relative to the parent block; multi-entry selectorMaps (from merged adjacent text nodes) are newline-separated 'charLen selectorMap' entries starting with a digit. Snapshot text nodes store `stream` instead: the raw character offset of the DOM text node's start within the body text stream, located via catalog.domMap.
 */
export type DomAnchor = {
  /**
   * Compact location string. Blocks: absolute (EPUB CFI path starting with '/', or snapshot CSS selector). EPUB text nodes: CFI suffix relative to the parent block.
   */
  selectorMap?: string;
  /**
   * Snapshot text nodes: offset of the DOM text node's first character within the body text stream (raw original characters, counted like a NodeIterator text walk over <body>). Element positions in the same stream are recorded in catalog.domMap.
   */
  stream?: number;
  /**
   * Position map between the node's text and the original DOM text it was extracted from (covers whitespace collapsing and NFC normalization). Space-separated 'nfcPos delta' pairs recorded where delta = nfcIdx - origIdx changes. Absent when all positions are 1:1. Decode: origPos = nfcPos - getDelta(deltaMap, nfcPos).
   */
  deltaMap?: string;
};
/**
 * Reference to the adjacent physical block that is part of the same logical block.
 *
 * @minItems 1
 */
export type PartRef = [number, ...number[]];
/**
 * Semantic flow classification assigned by layout extraction on top-level content blocks. Missing means body; new producers omit body.
 */
export type FlowClass = "auxiliary" | "excluded";

/**
 * Single outline entry.
 */
export interface OutlineItem {
  /**
   * Outline item title.
   */
  title: string;
  ref?: RefPath;
  target?: Target;
  children?: OutlineItem[];
}
/**
 * Per-page metadata for the source document.
 */
export interface PageInfo {
  /**
   * Page fingerprint for change detection.
   */
  fingerprint?: string;
  /**
   * True if the page was injected by the publisher.
   */
  injected?: boolean;
  /**
   * Effective PDF page view box in default user-space coordinates, before page rotation and UserUnit scaling: [x1, y1, x2, y2]. When CropBox and MediaBox differ and have a non-empty intersection, this is their intersection; otherwise it is MediaBox. Values can be negative when the effective box has a non-zero origin (e.g. [-50, -50, 562, 742]).
   *
   * @minItems 4
   * @maxItems 4
   */
  viewRect?: [number, number, number, number];
  /**
   * Effective intrinsic clockwise PDF page rotation, in degrees. In schema 1.1.0 and later, producers omit this property when 0; in earlier schemas, absence does not imply 0.
   */
  rotation?: 0 | 90 | 180 | 270;
  /**
   * Effective PDF UserUnit multiplier; one default user-space unit equals userUnit / 72 inch. In schema 1.1.0 and later, producers omit this property when 1; in earlier schemas, absence does not imply 1.
   */
  userUnit?: number;
  /**
   * Source of text on this page.
   */
  textSource?: "born-digital" | "ocr";
  /**
   * True if this page's SDT extraction used a degraded path or should be treated as lower confidence due to text, layout, or structure extraction issues.
   */
  extractionDegraded?: boolean;
  /**
   * Human-readable page label (e.g. 'i', '15', 'A-3').
   */
  label?: string;
  contentRange: PageContentRange;
}
/**
 * One element in the snapshot DOM skeleton (catalog.domMap). `index` is the element's 0-based position among its parent's element children in the full source DOM (not just skeleton nodes). `textStart`/`textLength` locate the element's subtree text within the body text stream. `flags` holds sibling-position bits used for selector generation and matching: 1 = first of its tag, 2 = last of its tag, 4 = last element child.
 */
export interface DomMapNode {
  /**
   * Lowercase tag name.
   */
  tag: string;
  /**
   * 0-based index among the parent's element children.
   */
  index: number;
  /**
   * DOM_MAP_* sibling-position bits. Omitted when 0.
   */
  flags?: number;
  /**
   * Element id attribute (unescaped).
   */
  id?: string;
  /**
   * id of the previous element sibling, for matching '#id + tag' selectors.
   */
  prevId?: string;
  /**
   * Body text-stream offset at element entry.
   */
  textStart: number;
  /**
   * Raw character length of the element's subtree text.
   */
  textLength: number;
  /**
   * Skeleton children, in document order. Omitted when empty.
   */
  children?: DomMapNode[];
}
/**
 * Paragraph block (inline text only).
 */
export interface ParagraphNode {
  /**
   * Discriminator for paragraphs.
   */
  type: "paragraph";
  /**
   * Inline content of the paragraph.
   */
  content: TextNode[];
  anchor: Anchor;
  /**
   * True if this block is a reference entry (e.g. bibliography item).
   */
  reference?: boolean;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * Inline text node with optional styling and references.
 */
export interface TextNode {
  /**
   * Plain text, including whitespace and newlines as-is.
   */
  text: string;
  style?: TextStyle;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  target?: Target;
  anchor?: Anchor;
}
/**
 * Inline text style flags.
 */
export interface TextStyle {
  bold?: boolean;
  italic?: boolean;
  sub?: boolean;
  sup?: boolean;
  monospace?: boolean;
}
/**
 * Heading block (inline text only).
 */
export interface HeadingNode {
  /**
   * Discriminator for headings.
   */
  type: "heading";
  /**
   * Inline content of the heading.
   */
  content: TextNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * Math block represented as inline text nodes.
 */
export interface MathNode {
  /**
   * Discriminator for math blocks.
   */
  type: "math";
  /**
   * Inline content of the math block.
   */
  content: TextNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * Image block with optional inline text (alt text, labels).
 */
export interface ImageNode {
  /**
   * Discriminator for images.
   */
  type: "image";
  /**
   * Inline text associated with the image.
   */
  content: TextNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * Blockquote block that contains other blocks.
 */
export interface BlockquoteNode {
  /**
   * Discriminator for blockquotes.
   */
  type: "blockquote";
  /**
   * Block content inside the blockquote.
   */
  content: ContentBlockNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * List block containing list items.
 */
export interface ListNode {
  /**
   * Discriminator for lists.
   */
  type: "list";
  /**
   * True for ordered lists, false for unordered. Defaults to false if omitted.
   */
  ordered?: boolean;
  /**
   * Start index for ordered lists (defaults to 1).
   */
  startIndex?: number;
  /**
   * Items in this list.
   *
   * @minItems 1
   */
  content: [ListItemNode, ...ListItemNode[]];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * Single list item: contains either inline text (simple items) or block children (items with nested structure).
 */
export interface ListItemNode {
  /**
   * Block type discriminator for list items.
   */
  type: "listitem";
  /**
   * Either inline text (TextNode[]) for simple items, or block children (ContentBlockNode[]) for items with nested structure.
   */
  content: [TextNode, ...TextNode[]] | [ContentBlockNode, ...ContentBlockNode[]];
  anchor: Anchor;
  /**
   * True if this block is a reference entry (e.g. bibliography item).
   */
  reference?: boolean;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
}
/**
 * Top-level table block.
 */
export interface TableNode {
  /**
   * Block type discriminator for tables.
   */
  type: "table";
  /**
   * Either inline text (TextNode[]) for simple/flat tables, or structured rows (TableRowNode[]) for fully parsed tables.
   */
  content: [TextNode, ...TextNode[]] | [TableRowNode, ...TableRowNode[]];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * Single table row.
 */
export interface TableRowNode {
  /**
   * Block type discriminator for table rows.
   */
  type: "tablerow";
  /**
   * Cells in this row. No raw text directly under a row.
   *
   * @minItems 1
   */
  content: [TableCellNode, ...TableCellNode[]];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
}
/**
 * Table cell container (header or data cell).
 */
export interface TableCellNode {
  /**
   * Block type discriminator for table cells.
   */
  type: "tablecell";
  /**
   * If true, this is a header cell (<th>); otherwise a data cell (<td>).
   */
  header?: boolean;
  /**
   * Axis for header cells: 'row' or 'column'.
   */
  axis?: "row" | "column";
  /**
   * Horizontal span of this cell. Default is 1 if omitted.
   */
  colspan?: number;
  /**
   * Vertical span of this cell. Default is 1 if omitted.
   */
  rowspan?: number;
  /**
   * Block content of the cell (paragraphs, lists, nested tables, etc.). Inline text must live inside those blocks.
   */
  content: ContentBlockNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
}
/**
 * Shared caption block (for tables, figures, images, groups, etc.).
 */
export interface CaptionNode {
  /**
   * Block type discriminator for captions.
   */
  type: "caption";
  /**
   * Inline content of the caption.
   */
  content: TextNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
/**
 * Note block used across the document (including table-local notes).
 */
export interface NoteNode {
  /**
   * Block type discriminator for notes.
   */
  type: "note";
  /**
   * Inline content of the note body.
   */
  content: TextNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
  /**
   * True if this block is a reference entry (e.g. bibliography item).
   */
  reference?: boolean;
}
/**
 * Preformatted block with whitespace-significant text.
 */
export interface PreformattedNode {
  /**
   * Discriminator for preformatted blocks.
   */
  type: "preformatted";
  /**
   * Inline content of the preformatted block.
   */
  content: TextNode[];
  anchor: Anchor;
  refs?: RefsArray;
  backRefs?: BackRefsArray;
  previousPart?: PartRef;
  nextPart?: PartRef;
  flowClass?: FlowClass;
}
